CREATE DATABASE IF NOT EXISTS prueba_tecnica;

DROP SCHEMA IF EXISTS usuarios cascade;
DROP SCHEMA IF EXISTS prueba cascade;

CREATE SCHEMA IF NOT EXISTS usuarios;
CREATE SCHEMA IF NOT EXISTS prueba;
